# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 01:49
from __future__ import unicode_literals

import account.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('photo', models.ImageField(storage=account.storage.AccountImageStorage(), upload_to='static/accountImage')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('verify_code', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
    ]
