# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-24 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import news.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('banner', models.ImageField(storage=news.storage.NewsImageStorage(), upload_to='static/news/banner')),
                ('status', models.IntegerField(choices=[(1, 'Online'), (2, 'Draft')])),
                ('viewed', models.IntegerField(null=0)),
                ('has_comment', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsOnSpecialPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'ABOUT US'), (2, 'INDEX TOP'), (3, 'INDEX'), (4, 'NEWS TOP')])),
                ('rank', models.IntegerField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsTopic'),
        ),
    ]
